#!/usr/bin/env sh
#
# Blaze allows language-agnostic literate-style programming
# Copyright (c) 2017 Tristram Oaten <tristram@oaten.name>
# License: MIT <https://opensource.org/licenses/MIT>
# Site: blaze.oat.sh
#

if [ "$1" = "--upgrade" ]
then
    sudo wget https://raw.githubusercontent.com/Gogotron/blaze/master/blaze -q -O $(readlink -f "$0")
    sudo chmod +x $(readlink -f "$0")
    echo "Blaze upgraded to latest"
    exit 0
fi

interpreter="$1"
script="$2"
shift $OPTIND; shift $OPTIND
script_args="$@"

awk '{ if (/^```/) { i++; next } if ( i % 2 == 1) { print } }'< "$script" > "$script.code"
$interpreter "$script.code" "$script_args"
exit_code=$?
rm "$script.code"
exit $exit_code
